### ISSUE TITLE
onnxruntime can't run the super_resolution model

### ISSUE THREAD

**Issue by snnn** [onnx/models#221]
2019-09-25 14:33:19.302285791 [E:onnxruntime:Default, runner.cc:342 RunTask] super_resolution:Invalid rank for input: input Got: 2 Expected: 4 Please fix either the inputs or the model.

**Comment by Naveenkhasyap** [comment]
@snnn check the input image preprocessing before passing it to run method , i think you are passing (H,W) of image instead of (H,W,C,A) as it is expected.

**Comment by snnn** [comment]
Hi @Naveenkhasyap, but I was using the test data provided with the model at here. Should the test data get fixed?

**Comment by Naveenkhasyap** [comment]
@snnn looks like the onnx model in model folder doesn't work , I tried to run the notebook given within this repo but if i refer to the onnx model from model folder it fails to load protobuf files , so then i tried with the link given to [download the model ](https://github.com/onnx/models/blob/master/vision/super_resolution/sub_pixel_cnn_2016/model/super_resolution.onnx) loading this model in onnx works perfectly fine, try running the notebook once and i use image as input instead of protobuf files given in this repo.

**Comment by prasanthpul** [comment]
is this still an issue?

**Comment by vinitra** [comment]
https://github.com/onnx/models/pull/228 -> should resolve this issue.
