### ISSUE TITLE
MNIST dimensions

### ISSUE THREAD

**Issue by alrevuelta** [onnx/models#244]
Hi, I'm implementing a dependancy free + pure C backend for ONNX and the first model that I'm running is the MNIST provided in [this repository](https://github.com/onnx/models/tree/master/vision/classification/mnist)

I have some questions regarding the dimensions. Please, find attached a screenshoot from `netron` visualizer:
- Input to `Conv` is 1x1x28x28, fair enough thats the image that is being processed.
- The weight vector to `Conv` is 8x1x5x5.
- And the output of `Conv` has a size of 1x8x28x28

So my question here is `how is the output dimension of Conv calculated?` I understand `kernel_shape` parameter, `strides`, `auto_pad` and `dilations` but I don't understand why the `Conv` matrix is not just 1x1x5x5. Isn't the first dimension the batch size? Why not 1x8x5x5 for example?

![image](https://user-images.githubusercontent.com/8811422/69666888-4c9cd080-108d-11ea-8ab1-36f62da9a89f.png)
![image](https://user-images.githubusercontent.com/8811422/69666207-2e82a080-108c-11ea-8acb-01eae760ccda.png)

This can be reproduced by using [netron](https://lutzroeder.github.io/netron/) and loading the MNIST model.

**Comment by vinitra** [comment]
Hi @alrevuelta, sorry for the late reply. If you take a look at the weight values being passed into the convolution, it becomes a bit more clear. We know [5x5] is the kernel shape of each convolution, but there are 8 different filters. 

![alt text](https://www.cntk.ai/jup/cntk103d_conv2d_final.gif)

**Comment by vinitra** [comment]
Hi @alrevuelta, sorry for the late reply. If you take a look at the weight values being passed into the convolution, it becomes a bit more clear. We know [5x5] is the kernel shape of each convolutional filter, but there are 8 different filters of [5x5] each, which means the conv output will have 8 different output sub-layers. The reason it's 1 x 8 x 28 x 28 instead of 1 x 8 x 5 x 5 is because of the `SAME_UPPER` auto_pad setting, which means "pad the input so that the output spatial size match the input".

I would recommend taking a look at the "CNN model creation" section of the original CNTK tutorial for a more in depth explanation. The GIF below and the tutorial explain it for a [3 x 3] kernel shape, but the logic is easily extended to the [5 x 5] case.

![alt text](https://www.cntk.ai/jup/cntk103d_conv2d_final.gif)
