### ISSUE TITLE
ValidationError “Field 'type' of attr is required but missing.” happened when invoking check_node function.

### ISSUE THREAD

**Issue by BruceDai** [onnx/models#9]
I'm green to DeepLearning, and I want to see the output of each node of Alex net by run_node function, but I met the following error.
```python
import onnx
model = onnx.load('/path/bvlc_alexnet/model.pb')
node = model.graph.node[0] #use the first node of op_type as "Conv"
onnx.checker.check_node(node)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 32, in checker
>     proto.SerializeToString(), ir_version)
> onnx.onnx_cpp2py_export.checker.ValidationError: Field 'type' of attr is required but missing.

```python
node
```

> input: "data_0"
> input: "conv1_w_0"
> input: "conv1_b_0"
> output: "conv1_1"
> name: ""
> op_type: "Conv"
> attribute {
>   name: "strides"
>   ints: 4
>   ints: 4
> }
> attribute {
>   name: "pads"
>   ints: 0
>   ints: 0
>   ints: 0
>   ints: 0
> }
> attribute {
>   name: "kernel_shape"
>   ints: 11
>   ints: 11
> }

I tried to add 'type' of attr by following codes
```python
from onnx import AttributeProto
attr = AttributeProto()
#I did't know which type was right, just tried to see the result of this workaround
#with 'AttributeProto.FLOAT' value.
attr.type = AttributeProto.FLOAT 
node.attribute.extend([attr])
node
```
> input: "data_0"
> input: "conv1_w_0"
> input: "conv1_b_0"
> output: "conv1_1"
> name: ""
> op_type: "Conv"
> attribute {
>   name: "strides"
>   ints: 4
>   ints: 4
> }
> attribute {
>   name: "pads"
>   ints: 0
>   ints: 0
>   ints: 0
>   ints: 0
> }
> attribute {
>   name: "kernel_shape"
>   ints: 11
>   ints: 11
> }
> **attribute {
>   type: FLOAT
> }**

```python
onnx.checker.check_node(node)
```
, still got the same error.

**Comment by BruceDai** [comment]
@bddppq would you please show me how to add this 'type' attribute, thanks.

**Comment by bddppq** [comment]
"type" is a field in AttributeProto, so it should be (e.g.)
```
node.attribute[0].type = AttributeProto.INT
```

Actually the `type` field is only required to be present in models with `ir_version >= 0x00000002`. Looks like the model files in the model zoo are still of version 1 and so it's ok to not have this field. However, checker will need to know this context in order to perform the correct check (there is an optional argument in `check_node` to supply the context to the checker), otherwise it will just assume it's checking against the newest ir_version.

We should update the models to the newest ir_version.

**Comment by bddppq** [comment]
https://github.com/onnx/models/issues/14

**Comment by BruceDai** [comment]
@bddppq thank you!
